<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="flex-container">


        <?php require 'right-box.phtml'; ?>


        <div class="left-box-pad-320">
            <div class="box-wrapper">
                <div class="box-padding">

                    <h1><?=$title?></h1>
                    <?=$content?>

                </div>
            </div>
        </div>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
