<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$forum->title?></h1>
        <p><?=$forum->description?></p>


        <div class="test__forum-item">
            <?php foreach ($forum->subforums as $subForum) { ?>
                <div class="sub-forum">
                    <div class="sub-forum__info">
                        <h3 class="sub-forum__title"><a href="/forum/sub-forum?id=<?=$subForum->id?>"><?=$subForum->title?></a></h3>
                        <p class="sub-forum__description"><?=$subForum->description?></p>
                    </div>
                    <div class="sub-forum__stat sub-forum-stat">
                        <div class="sub-forum-stat__entry">Количество тем:</div>
                        <div class="sub-forum-stat__entry"><?=$subForum->topics_count?></div>
                        <div class="sub-forum-stat__entry">Количество ответов:</div>
                        <div class="sub-forum-stat__entry"><?=$subForum->posts_count?></div>

                        <?php if ($subForum->last_post_id) { ?>
                            <div class="sub-forum-stat__entry">Последний ответ:</div>
                            <div class="sub-forum-stat__entry"><?=$subForum->last_post_modified?></div>

                            <div class="sub-forum-stat__entry sub-forum-stat__entry_post-title">
                                <a href="/forum/to-post?id=<?=$subForum->last_post_id?>"><?=$subForum->last_topic_title?></a>
                            </div>
                            <div class="sub-forum-stat__entry sub-forum-stat__entry_post-author">
                                Автор:
                                <a href="/user?id=<?=$subForum->last_post_author_id?>"><?=$subForum->last_post_author_login?></a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
