<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$forum->title?></h1>
        <p><?=$forum->description?></p>


        <div class="test__forum-item">
            <?php foreach ($forum->subforums as $subForum) { ?>
                <div class="sub-forum">
                    <div class="sub-forum__info">
                        <h3 class="sub-forum__title"><a href="/forum/sub-forum?id=<?=$subForum->id?>"><?=$subForum->title?></a></h3>
                        <p class="sub-forum__description"><?=$subForum->description?></p>
                    </div>
                    <div class="sub-forum__stat forum-stat">
                        <div class="forum-stat__item forum-stat__item_iconic">
                            <i class="icon icon-file-text-o" title="Количество тем"></i>
                            <?=$subForum->topics_count?>
                        </div>
                        <div class="forum-stat__item forum-stat__item_iconic">
                            <i class="icon icon-comment-o" title="Количество ответов"></i> <?= $subForum->posts_count ?>
                        </div>

                        <?php if ($subForum->last_post_id) { ?>
                            <div class="forum-stat__item">
                                <div class="forum-stat__name">Последний ответ:</div>
                                <div class="forum-stat__value"><?=$subForum->last_post_modified?></div>
                            </div>
                            <div class="forum-stat__item forum-stat__item_post-title">
                                <a href="/forum/to-post?id=<?=$subForum->last_post_id?>"><?=$subForum->last_topic_title?></a>
                            </div>
                            <div class="forum-stat__item forum-stat__item_post-author">
                                Автор:
                                <?php if ($subForum->last_post_author_id) { ?>
                                    <a href="/user?id=<?=$subForum->last_post_author_id?>"><?=$subForum->last_post_author_login?></a>
                                <?php } else { ?>
                                    [ <?=View::$language->forum_forum_last_post_author_has_removed?> ]
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
