<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$subForum->title?></h1>
        <p><?=$subForum->description?></p>


        <?php require 'pagination.phtml'; ?>


        <style type="text/css">

           .test__sub-forum-box {
                padding: 0 0 40px 0;
            }

            .test__sub-forum-topic {
                display: flex;
                padding: 5px 5px 10px 5px;
                border: solid 1px #d2d2d2;
                border-bottom: none;
            }

            .test__sub-forum-topic:last-child {
                border-bottom: solid 1px #d2d2d2;
            }

            .test__sub-forum-topic-icons {
                width: 30px;
            }

            .test__sub-forum-topic-icons .icon {
                cursor: help;
                margin: 2px 0;
            }

            .test__sub-forum-topic-info {
                flex: 1;
            }

            .test__sub-forum-topic-stat {
                padding: 0 0 0 10px;
                width: 230px;
            }

            .test__sub-forum-topic-stat-name,
            .test__sub-forum-topic-stat-value {
                float: left;
            }

            .test__sub-forum-topic-stat-name {
                width: 90px;
            }

            .test__sub-forum-topic-stat-value {
                max-width: 140px;
            }

            .test__sub-forum-topic-actions {
                width: 30px;
                text-align: right;
            }

            .test__sub-forum-topic-actions a {
                margin: 2px 0;
            }

            @media (max-width: 640px) {

                .test__sub-forum-topic {
                    position: relative;
                    display: block;
                }

                .test__sub-forum-topic-icons {
                    float: left;
                }

                .test__sub-forum-topic-info,
                .test__sub-forum-topic-stat {
                    margin: 0 0 0 30px;
                    width: auto;
                }

                .test__sub-forum-topic-info {
                    padding: 0 30px 0 0;
                }

                .test__sub-forum-topic-info-stat {
                    padding: 0 0 10px 0;
                }

                .test__sub-forum-topic-stat {
                    padding: 0;
                }

                .test__sub-forum-topic-actions {
                    position: absolute;
                    top: 5px;
                    right: 5px;
                }

            }

        </style>


        <?php if (!$topics) { ?>
            <div class="alert alert_info">Нет топиков</div>
        <?php } else { ?>

            <div class="test__sub-forum-box">

                <?php foreach ($topics as $topic) { ?>
                    <div class="test__sub-forum-topic">
                        <div class="test__sub-forum-topic-icons">
                            <?php if ($topic->is_closed) { ?>
                                <span class="icon icon-border icon-lock"
                                        title="Тема закрыта"></span>
                            <?php } ?>
                            <?php if ($topic->is_locked) { ?>
                                <span class="icon icon-border icon-paperclip"
                                        title="Тема закреплена"></span>
                            <?php } ?>
                            <?php if ($topic->is_important) { ?>
                                <span class="icon icon-border icon icon-warning"
                                        title="Тема помечена важной"></span>
                            <?php } ?>
                        </div>
                        <div class="test__sub-forum-topic-info">
                            <h3>
                                <a href="/forum/topic?id=<?=$topic->id?>"><?=$topic->title?></a>
                                <?php if ($topic->posts_count) { ?>
                                    <a href="/forum/to-post?id=<?=$topic->last_post_id?>"
                                        title="Перейти к последнему ответу">&raquo;</a>
                                <?php } ?>
                            </h3>
                            <p><?=$topic->description?></p>
                            <div class="test__sub-forum-topic-info-stat">
                                <?=$topic->creation_date?>,
                                <a href="/user?id=<?=$topic->authored_by?>"><?=$topic->author_login?></a>
                            </div>
                        </div>
                        <div class="test__sub-forum-topic-stat">
                            <div class="test__sub-forum-topic-stat-name">Просмотров:</div>
                            <div class="test__sub-forum-topic-stat-value"><?=$topic->views_count?></div>
                            <div class="clear"></div>
                            <div class="test__sub-forum-topic-stat-name">Ответов:</div>
                            <div class="test__sub-forum-topic-stat-value"><?=$topic->posts_count?></div>
                            <div class="clear"></div>
                            <?php if ($topic->posts_count) { ?>
                                <div class="test__sub-forum-topic-stat-name">Обновление:</div>
                                <div class="test__sub-forum-topic-stat-value">
                                    <a href="/forum/to-post?id=<?=$topic->last_post_id?>"><?=$topic->last_modified?></a>
                                </div>
                                <div class="clear"></div>
                                <div class="test__sub-forum-topic-stat-name">Автор ответа:</div>
                                <div class="test__sub-forum-topic-stat-value">
                                    <a href="/user?id=<?=$topic->last_post_author_id?>"><?=$topic->last_post_author_login?></a>
                                </div>
                                <div class="clear"></div>
                            <?php } ?>
                        </div>
                        <div class="test__sub-forum-topic-actions">
                            <?php if (true /*Member::hasPermission('forum_topic_remove')*/) { ?>
                                <a class="icon icon-border icon-remove"
                                    href="#remove"
                                    data-id="<?=$topic->id?>"
                                    onclick="return false;"
                                    title="Удалить"></a>
                            <?php } ?>
                            <?php if (true /*Member::hasPermission('forum_topic_edit')*/) { ?>
                                <a class="icon icon-border icon-pencil"
                                    href="#edit"
                                    data-id="<?=$topic->id?>"
                                    onclick="return false;"
                                    title="Правка"></a>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>

            </div>

        <?php } ?>



        <?php /*if ($topics) { ?>
            <table class="forum" cellspacing="1">
                <tr class="table-heading">
                    <td class="target-info">
                        <div class="td-wrapper">Название топика</div>
                    </td>
                    <td>Автор</td>
                    <td>Ответов</td>
                    <td>Просмотров</td>
                    <td class="last-update">
                        <div class="td-wrapper">Последнее сообщение</div>
                    </td>
                </tr>
                <?php foreach ($topics as $topic) { ?>
                    <tr>
                        <td class="target-info">
                            <div class="td-wrapper">
                                <div class="title">

                                    <?php if (Member::hasPermission('forum_topic_remove')) { ?>
                                        <a href="#remove"
                                            data-id="<?=$topic->id?>"
                                            onclick="return false;"
                                            title="Удалить">[remove img]</a>
                                    <?php } ?>
                                    <?php if (Member::hasPermission('forum_topic_edit')) { ?>
                                        <a href="#edit"
                                            data-id="<?=$topic->id?>"
                                            onclick="return false;"
                                            title="Правка">[edit img]</a>
                                    <?php } ?>

                                    <?php if ($topic->is_closed) { ?>
                                        [closed img]
                                    <?php } ?>
                                    <?php if ($topic->is_locked) { ?>
                                        [locked img]
                                    <?php } ?>
                                    <?php if ($topic->is_important) { ?>
                                        [important img]
                                    <?php } ?>

                                    <a href="/forum/topic?id=<?=$topic->id?>"><?=$topic->title?></a>

                                </div>
                                <div class="description"><?=$topic->description?></div>
                            </div>
                        </td>
                        <td class="author-info" width="140">
                                <div class="author"><a href="/user?id=<?=$topic->authored_by?>"><?=$topic->author_login?></a></div>
                        </td>
                        <td class="answers-count">
                            <div class="td-wrapper"><?=$topic->posts_count?></div>
                        </td>
                        <td class="answers-count">
                            <div class="td-wrapper"><?=$topic->views_count?></div>
                        </td>
                        <td class="last-update">
                            <div class="td-wrapper">
                                <?php if ($topic->last_post_id) { ?>
                                    <div class="topic"><a href="/forum/to-post?id=<?=$topic->last_post_id?>"><?=$topic->last_post_modified?></a></div>
                                    <div class="author"><a href="/user?id=<?=$topic->last_post_author_id?>"><?=$topic->last_post_author_login?></a></div>
                                <?php } else { ?>
                                    <div class="topic">нет</div>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        <?php } else { ?>
            <div class="alert alert_info">Нет топиков</div>
        <?php }*/ ?>


        <?php require 'pagination.phtml'; ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
