<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <table class="forum" cellspacing="1">
            <tr class="table-heading">
                <td class="target-info">
                    <div class="td-wrapper">Название категории/форума</div>
                </td>
                <td class="topics-count">
                    <div class="td-wrapper">Тем</div>
                </td>
                <td class="answers-count">
                    <div class="td-wrapper">Ответов</div>
                </td>
                <td class="last-update">
                    <div class="td-wrapper">Последнее сообщение</div>
                </td>
            </tr>
            <?php foreach (range(0, 10) as $item) { ?>
                <tr>
                    <td class="target-info">
                        <div class="td-wrapper">
                            <div class="title"><a href="#">Название категории/форума/топика</a></div>
                            <div class="description">Описание категории/форума/топика</div>
                        </div>
                    </td>
                    <td class="topics-count">
                        <div class="td-wrapper">13</div>
                    </td>
                    <td class="answers-count">
                        <div class="td-wrapper">2342</div>
                    </td>
                    <td class="last-update">
                        <div class="td-wrapper">
                            <div class="date-time">2014-12-05 13:38:21</div>
                            <div class="topic"><a href="#">Название топика</a></div>
                            <div class="author"><a href="#">Логин пользователя</a></div>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
