<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$subForum->title?></h1>
        <p><?=$subForum->description?></p>


        <?php require 'pagination.phtml'; ?>


        <?php if (!$topics) { ?>
            <div class="alert alert_info">Нет топиков</div>
        <?php } else { ?>

            <div class="topics">

                <?php foreach ($topics as $topic) { ?>
                    <div class="topics__item topics-item">
                        <div class="topics-item__icons topic-icons">
                            <?php if ($topic->is_closed) { ?>
                                <span class="icon icon-lock topic-icons__icon topic-icons__icon_closed"
                                      title="Тема закрыта"></span>
                            <?php } ?>
                            <?php if ($topic->is_locked) { ?>
                                <span class="icon icon-paperclip topic-icons__icon topic-icons__icon_pinned"
                                      title="Тема закреплена"></span>
                            <?php } ?>
                            <?php if ($topic->is_important) { ?>
                                <span class="icon icon icon-warning topic-icons__icon topic-icons__icon_important"
                                      title="Тема помечена важной"></span>
                            <?php } ?>
                        </div>
                        <div class="topics-item__actions topic-actions">
                            <?php if (true /*Member::hasPermission('forum_topic_remove')*/) { ?>
                                <a class="icon icon-remove topic-actions__action topic-actions__action_remove"
                                   href="#remove"
                                   data-id="<?=$topic->id?>"
                                   onclick="return false;"
                                   title="Удалить"></a>
                            <?php } ?>
                            <?php if (true /*Member::hasPermission('forum_topic_edit')*/) { ?>
                                <a class="icon icon-pencil topic-actions__action topic-actions__action_edit"
                                   href="#edit"
                                   data-id="<?=$topic->id?>"
                                   onclick="return false;"
                                   title="Правка"></a>
                            <?php } ?>
                        </div>
                        <div class="topics-item__info test__sub-forum-topic-info">
                            <h3 class="topics-item__title">
                                <a href="/forum/topic?id=<?=$topic->id?>"><?=$topic->title?></a>
                                <?php if ($topic->posts_count) { ?>
                                    <a href="/forum/to-post?id=<?=$topic->last_post_id?>"
                                        title="Перейти к последнему ответу">&raquo;</a>
                                <?php } ?>
                            </h3>
                            <p><?=$topic->description?></p>
                            <div class="">
                                <?=$topic->creation_date?>,
                                <?php if ($topic->author_id) { ?>
                                    <a href="/user?id=<?=$topic->author_id?>"><?=$topic->author_login?></a>
                                <?php } else { ?>
                                    [ <?=View::$language->forum_sub_forum_topic_author_has_removed?> ]
                                <?php } ?>
                            </div>
                        </div>
                        <div class="topics-item__stat forum-stat">
                            <div class="forum-stat__item forum-stat__item_iconic">
                                <i class="icon icon-eye" title="Количество просмотров"></i> <?= $topic->views_count ?>
                            </div>
                            <div class="forum-stat__item forum-stat__item_iconic">
                                <i class="icon icon-comment-o" title="Количество ответов"></i> <?= $topic->posts_count ?>
                            </div>
                            <?php if ($topic->posts_count) { ?>
                                <div class="forum-stat__item">
                                    <div class="forum-stat__name">Обновление:</div>
                                    <div class="forum-stat__value">
                                        <a href="/forum/to-post?id=<?= $topic->last_post_id ?>"><?= $topic->last_modified ?></a>
                                    </div>
                                </div>
                                <div class="forum-stat__item">
                                    <div class="forum-stat__name">Автор ответа:</div>
                                    <div class="forum-stat__value">
                                        <?php if ($topic->last_post_author_id) { ?>
                                            <a href="/user?id=<?= $topic->last_post_author_id ?>"><?= $topic->last_post_author_login ?></a>
                                        <?php } else { ?>
                                            [ <?=View::$language->forum_sub_forum_last_post_author_has_removed?> ]
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>

            </div>

        <?php } ?>


        <?php require 'pagination.phtml'; ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
