<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$h1?></h1>
        <p>
            <?php foreach ($filters as $k => $filter) { ?>
                <?php

                    $separator = $k ? ' | ' : '';
                    $className = $filter->current ? ' class="current-filter"' : '';

                ?>
                <?=$separator?><a<?=$className?> href="<?=$filter->url?>"><?=$filter->title?></a>
            <?php } ?>
        </p>


        <?php require 'pagination.phtml'; ?>


        <table class="forum" cellspacing="1">
            <tr class="table-heading">
                <td class="target-info">
                    <div class="td-wrapper">Название топика</div>
                </td>
                <td>Автор</td>
                <td>Ответов</td>
                <td>Просмотров</td>
                <td class="last-update">
                    <div class="td-wrapper">Последнее сообщение</div>
                </td>
            </tr>
            <?php foreach ($topics as $topic) { ?>
                <tr>
                    <td class="target-info">
                        <div class="td-wrapper">
                            <div class="title">

                                <?php if (true /*Member::hasPermission('forum_topic_remove')*/) { ?>
                                    <a href="#remove"
                                        data-id="<?=$topic->id?>"
                                        onclick="return false;"
                                        title=" Удалить ">[remove img]</a>
                                <?php } ?>
                                <?php if (true /*Member::hasPermission('forum_topic_edit')*/) { ?>
                                    <a href="#edit"
                                        data-id="<?=$topic->id?>"
                                        onclick="return false;"
                                        title=" Правка ">[edit img]</a>
                                <?php } ?>

                                <?php if ($topic->is_closed) { ?>
                                    [closed img]
                                <?php } ?>
                                <?php if ($topic->is_important) { ?>
                                    [important img]
                                <?php } ?>

                                <a href="/forum/topic?id=<?=$topic->id?>"><?=$topic->title?></a>

                            </div>
                            <div class="description"><?=$topic->description?></div>
                        </div>
                    </td>
                    <td class="author-info" width="140">
                            <div class="author"><a href="/user?id=<?=$topic->authored_by?>"><?=$topic->author_login?></a></div>
                    </td>
                    <td class="answers-count">
                        <div class="td-wrapper"><?=$topic->posts_count?></div>
                    </td>
                    <td class="answers-count">
                        <div class="td-wrapper"><?=$topic->views_count?></div>
                    </td>
                    <td class="last-update">
                        <div class="td-wrapper">
                            <?php if ($topic->last_post_id) { ?>
                                <div class="topic"><a href="/forum/to-post?id=<?=$topic->last_post_id?>"><?=$topic->last_post_modified?></a></div>
                                <div class="author"><a href="/user?id=<?=$topic->last_post_author_id?>"><?=$topic->last_post_author_login?></a></div>
                            <?php } else { ?>
                                <div class="topic">нет</div>
                            <?php } ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>


        <?php require 'pagination.phtml'; ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
