<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$h1?></h1>
        <p>&nbsp;</p>


        <?php foreach ($forumsTree as $forum) { ?>
            <table class="forum" cellspacing="1">
                <tr class="table-heading">
                    <td class="target-info">
                        <div class="td-wrapper">
                            <a class="forum-title" href="/forum/forum?id=<?=$forum->id?>"><?=$forum->title?></a>
                            <i>(<?=$forum->description?>)</i>
                        </div>
                    </td>
                    <td class="topics-count">
                        <div class="td-wrapper">Тем</div>
                    </td>
                    <td class="answers-count">
                        <div class="td-wrapper">Ответов</div>
                    </td>
                    <td class="last-update">
                        <div class="td-wrapper">Последнее сообщение</div>
                    </td>
                </tr>
                <?php foreach ($forum->subforums as $subForum) { ?>
                    <tr>
                        <td class="target-info">
                            <div class="td-wrapper">
                                <div class="title"><a href="/forum/sub-forum?id=<?=$subForum->id?>"><?=$subForum->title?></a></div>
                                <div class="description"><?=$subForum->description?></div>
                            </div>
                        </td>
                        <td class="topics-count">
                            <div class="td-wrapper"><?=$subForum->topics_count?></div>
                        </td>
                        <td class="answers-count">
                            <div class="td-wrapper"><?=$subForum->posts_count?></div>
                        </td>
                        <td class="last-update">
                            <div class="td-wrapper">
                                <?php if ($subForum->last_post_id) { ?>
                                    <div class="date-time"><?=$subForum->last_post_modified?></div>
                                    <div class="topic"><a href="forum/to-post?id=<?=$subForum->last_post_id?>"><?=$subForum->last_topic_title?></a></div>
                                    <div class="author"><a href="/user?id=<?=$subForum->last_post_author_id?>"><?=$subForum->last_post_author_login?></a></div>
                                <?php } else { ?>
                                    <div class="topic">нет</div>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        <?php } ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
