<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$topic->topic_title?></h1>
        <p><?=$topic->topic_description?></p>


        <?php require 'pagination.phtml'; ?>


        <div class="forum-topic">
            <?php foreach ($posts as $p => $post) { ?>

                <div class="topic-post-anchor"><a name="topic-post-<?=$post->id?>"></a></div>
                <div id="topic-post-<?=$post->id?>"
                        class="topic-post topic-post_<?= ($p % 2 == 0) ? 'even' : 'odd' ?>">
                    <div class="topic-post-author">
                        <div class="topic-post-author__user">
                            <div class="topic-post-author__name">
                                <a href="/user?id=<?=$post->author_id?>"><?=$post->author_login?></a>
                            </div>
                            <div class="topic-post-author__role"><?=$post->author_group_name?></div>
                        </div>
                        <div class="topic-post-author__avatar">
                            <a href="/user?id=<?=$post->author_id?>">
                                <img src="//<?=$hosts->st?>/images/no-avatar.png">
                            </a>
                        </div>
                        <div class="topic-post-author__counter">
                            Сообщений: <?=$post->author_posts_count?>
                            <div class="topic-post-date-time"><?=$post->creation_date?></div>
                        </div>
                    </div>
                    <div class="topic-post-body">
                        <div class="topic-post-body__panel topic-post-body__panel_top">
                            <div class="topic-post-date-time"><?=$post->creation_date?></div>

                            <div class="topic-post-actions">

                                <?php if (!$post->topic_start /*&& Member::hasPermission('forum_post_remove')*/) { ?>
                                    <a class="topic-post-action topic-post-action_button"
                                        href="#remove"
                                        data-id="<?=$post->id?>"
                                        onclick="return false;">
                                        <?=view::$language->forum_topic_remove?>
                                    </a>
                                <?php } ?>
                                <?php if (true /*$_member->id == $post->author_id || member::hasPermission('forum_post_edit')*/) { ?>
                                    <a class="topic-post-action topic-post-action_button"
                                        href="#edit"
                                        data-id="<?=$post->id?>"
                                        onclick="return false;">
                                        <?=view::$language->forum_topic_edit?>
                                    </a>
                                <?php } ?>

                                <a class="topic-post-action topic-post-action_link" href="/forum/to-post?id=<?=$post->id?>">#<?=($postsCountOffset + $p)?></a>

                            </div>
                        </div>
                        <div class="topic-post-content">
                            <?=$post->post_html?>
                        </div>
                        <div class="topic-post-body__panel topic-post-body__panel_bottom">
                            <div class="topic-post-info">
                                <?php if ($post->is_modified) { ?>
                                    Отредактировано: <?=$post->last_modified?>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>


        <?php require 'pagination.phtml'; ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
