<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$topic->topic_title?></h1>


        <?php require 'pagination.phtml'; ?>


        <div class="forum-topic">
            <?php foreach ($posts as $p => $post) { ?>

                <div class="forum-topic-post-anchor">
                    <a name="post-<?=$post->id?>"></a>
                </div>
                <div class="forum-topic-post forum-topic-post-<?= ($p % 2 == 0) ? 'even' : 'odd' ?>">
                    <div class="forum-topic-post-context-separator"></div>
                    <div class="forum-topic-post-author">
                        <div class="forum-topic-post-author-name">
                            <a href="/user?id=<?=$post->author_id?>"><?=$post->author_login?></a>
                        </div>
                        <div class="forum-topic-post-author-role"><?=$post->author_group_name?></div>
                        <div class="forum-topic-post-author-avatar">
                            <a href="/user?id=<?=$post->author_id?>">
                                <img src="//<?=$hosts->st?>/images/no-avatar.png">
                            </a>
                        </div>
                        <div class="forum-topic-post-author-counter">
                            Сообщений: <?=$post->author_posts_count?>
                        </div>
                    </div>
                    <div class="forum-topic-post-body">
                        <div class="forum-topic-post-body-actions">

                            <div class="forum-topic-post-date-time"><?=$post->creation_date?></div>

                            <?php if (!$post->topic_start /*&& Member::hasPermission('forum_post_remove')*/) { ?>
                                <a class="action forum-topic-post-remove-action"
                                    href="#remove"
                                    data-id="<?=$post->id?>"
                                    onclick="return false;">
                                    <?=view::$language->forum_topic_remove?>
                                </a>
                            <?php } ?>

                            <?php if (true /*$_member->id == $post->author_id || member::hasPermission('forum_post_edit')*/) { ?>
                                <a class="action forum-topic-post-edit-action"
                                    href="#edit"
                                    data-id="<?=$post->id?>"
                                    onclick="return false;">
                                    <?=view::$language->forum_topic_edit?>
                                </a>
                            <?php } ?>

                            <a class="anchor"
                                href="/forum/to-post?id=<?=$post->id?>">#<?=($postsCountOffset + $p)?></a>

                        </div>
                        <div class="forum-topic-post-body-content">
                            <?=$post->post_html?>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="forum-topic-post-info-wrapper">
                        <div class="forum-topic-post-info">
                            <?php if ($post->is_modified) { ?>
                                Отредактировано: <?=$post->last_modified?>
                            <?php } ?>
                        </div>
                    </div>
                </div>

            <?php } ?>
        </div>


        <?php require 'pagination.phtml'; ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
