<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?=$subForumTree->title?></h1>
        <p><?=$subForumTree->description?></p>


        <table class="forum" cellspacing="1">
            <tr class="table-heading">
                <td class="target-info">
                    <div class="td-wrapper">Название топика</div>
                </td>
                <td>Ответов</td>
                <td class="last-update">
                    <div class="td-wrapper">Последнее сообщение</div>
                </td>
            </tr>
            <?php foreach ($subForumTree->topics as $topic) { ?>
                <tr>
                    <td class="target-info">
                        <div class="td-wrapper">
                            <div class="title"><a href="/forum/topic?id=<?=$topic->id?>"><?=$topic->title?></a></div>
                            <div class="description"><?=$topic->description?></div>
                        </div>
                    </td>
                    <td class="answers-count">
                        <div class="td-wrapper"><?=$topic->posts_count?></div>
                    </td>
                    <td class="last-update">
                        <div class="td-wrapper">
                            <?php if ($topic->last_post_id) { ?>
                                <div class="topic"><a href="forum/to-post?id=<?=$topic->last_post_id?>"><?=$topic->last_post_modified?></a></div>
                                <div class="author"><a href="/user?id=<?=$topic->last_post_author_id?>"><?=$topic->last_post_author_login?></a></div>
                            <?php } else { ?>
                                <div class="topic">нет</div>
                            <?php } ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
