<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <?php require 'breadcrumbs.phtml'; ?>


    <div class="box-padding">


        <h1><?= $h1 ?></h1>


        <?php foreach ($forumsTree as $forum) { ?>
            <div class="forum">
                <h2 class="forum__title"><a href="/forum/forum?id=<?= $forum->id ?>"><?= $forum->title ?></a></h2>
                <p class="forum__description"><?= $forum->description ?></p>
                <?php foreach ($forum->subforums as $subForum) { ?>
                    <div class="sub-forum">
                        <div class="sub-forum__info">
                            <h3 class="sub-forum__title"><a href="/forum/sub-forum?id=<?= $subForum->id ?>"><?= $subForum->title ?></a></h3>
                            <p class="sub-forum__description"><?= $subForum->description ?></p>
                        </div>
                        <div class="sub-forum__stat forum-stat">
                            <div class="forum-stat__item forum-stat__item_iconic">
                                <i class="icon icon-file-text-o" title="Количество тем"></i>
                                <?=$subForum->topics_count?>
                            </div>
                            <div class="forum-stat__item forum-stat__item_iconic">
                                <i class="icon icon-comment-o" title="Количество ответов"></i>
                                <?= $subForum->posts_count ?>
                            </div>

                            <?php if ($subForum->last_post_id) { ?>
                                <div class="forum-stat__item">
                                    <div class="forum-stat__name">Последний ответ:</div>
                                    <div class="forum-stat__value"><?=$subForum->last_post_modified?></div>
                                </div>
                                <div class="forum-stat__item forum-stat__item_post-title">
                                    <a href="/forum/to-post?id=<?=$subForum->last_post_id?>"><?=$subForum->last_topic_title?></a>
                                </div>
                                <div class="forum-stat__item forum-stat__item_post-author">
                                    Автор:
                                    <a href="/user?id=<?=$subForum->last_post_author_id?>"><?=$subForum->last_post_author_login?></a>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
