<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width">
        <meta name="Description" content="<?=$meta_description?>">
        <meta name="Keywords" content="<?=$meta_keywords?>">
        <link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico">
        <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/favicon.ico">
        <link rel="stylesheet" type="text/css" href="//<?=$hosts->st?>/styles/jquery.fancybox.css">
        <link rel="stylesheet" type="text/css" href="//<?=$hosts->st?>/styles/main.css">
        <link rel="stylesheet" type="text/css" href="//<?=$hosts->st?>/themes/standard/styles/standard.css">
        <script type="text/javascript" src="//<?=$hosts->st?>/js/jquery-1.7.2.js"></script>
        <script type="text/javascript" src="//<?=$hosts->st?>/js/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="//<?=$hosts->st?>/js/main.js"></script>
        <title><?=$title?></title>
    </head>
    <body>

        <div id="container">


