

    <div class="main-menu" id="main-menu">
        <a class="main-menu__item" href="/">PHP.SU</a>
        <div class="main-menu__item main-menu__item_composite main-menu-item-composite">
            <div class="main-menu-item-composite__icon-wrapper">
                <a class="main-menu-item-composite__icon" href="/forum/filter?by=last" title="Новые сообщения"></a>
            </div>
            <a class="main-menu-item-composite__link" href="/forum">Форум</a>
        </div>
        <a class="main-menu__item" href="/articles">Статьи</a>
        <a class="main-menu__item" href="/documentation">Документация</a>
        <a class="main-menu__item" href="/scripts">PHP скрипты</a>
        <a class="main-menu__item" href="/books">Книги/Учебники</a>
        <a class="main-menu__item" href="/downloads">Download</a>
        <a class="main-menu__item" href="/search">Поиск</a>
        <a class="main-menu__item" href="/help">Помощь</a>
    </div><!-- #top-menu -->


