

    <div id="main-menu">
        <a href="/">PHP.SU</a>
        <a id="forum-link-last" href="/forum/filter?by=last" title="Новые сообщения"></a>
        <a id="forum-link" href="/forum">Форум</a>
        <a href="/articles">Статьи</a>
        <a href="/documentation">Документация</a>
        <a href="/scripts">PHP скрипты</a>
        <a href="/books">Книги/Учебники</a>
        <a href="/downloads">Download</a>
        <a href="/search">Поиск</a>
        <a href="/help">Помощь</a>
        <div class="clear"></div>
    </div><!-- #top-menu -->


