

    <div class="main-menu" id="main-menu">
        <div class="main-menu__item main-menu__item_button main-menu-compact-button">
            <div class="main-menu-compact-button__hamburger"></div>
            <div class="main-menu-compact-button__text">Меню</div>
        </div>
        <div class="main-menu-compact">
            <a class="main-menu__item" href="/"><span>PHP.SU</span></a>
            <div class="main-menu__item main-menu__item_composite main-menu-item-composite">
                <a class="main-menu-item-composite__icon" href="/forum/tracker" title="Последние сообщения"></a>
                <a class="main-menu-item-composite__link" href="/forum"><span>Форум</span></a>
            </div>
            <a class="main-menu__item" href="/articles"><span>Статьи</span></a>
            <a class="main-menu__item" href="/documentation"><span>Документация</span></a>
            <a class="main-menu__item" href="/scripts"><span>PHP скрипты</span></a>
            <a class="main-menu__item" href="/books"><span>Книги/Учебники</span></a>
            <a class="main-menu__item" href="/downloads"><span>Download</span></a>
            <a class="main-menu__item" href="/search"><span>Поиск</span></a>
            <a class="main-menu__item" href="/help"><span>Помощь</span></a>
        </div>
    </div><!-- .main-menu -->


