<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>
    <?php require 'main-menu.phtml'; ?>


    <div class="breadcrumbs">
        <a href="#">Какие-то</a> &raquo;
        <a href="#">Хлебные</a> &raquo;
        <a href="#">Крошки</a> &raquo;
        <span>Рассыпались по сайту</span>
    </div>


    <?php require 'right-box.phtml'; ?>


    <div class="left-box-pad-320">
        <div class="box-wrapper">
            <div class="box-padding">

                <h1>Nulla eu risus sollicitudin</h1>


                <p>
                    <pre><?php var_dump(Member::getProfile()); ?></pre>
                </p>


                <p>
                    Vivamus magna ligula, blandit et risus sit amet, pulvinar cursus lacus.
                    Nulla viverra nulla quis maximus malesuada.
                    Nam commodo, nisl vitae auctor vestibulum, nulla turpis interdum mi,
                    ac rutrum velit velit ac ipsum.
                    Nulla eu risus <a href="#">sollicitudin</a>, placerat felis vitae, mattis lorem.
                    Donec porttitor semper arcu non viverra.
                    Etiam viverra interdum purus id porta.
                    Proin et sem sed velit cursus fringilla.
                    Integer laoreet massa eu justo ornare faucibus.
                    Nunc tincidunt egestas elit ac maximus.
                    Nam porttitor eget metus vel vulputate. Sed et faucibus enim.
                </p>
                <p>
                    Sed vel orci aliquam, consequat quam quis, suscipit tellus.
                    Etiam at consectetur enim. Sed et mauris lacus.
                    Fusce rutrum leo ante, <a href="#">placerat congue mauris</a> tincidunt vel.
                    Nunc eget nisi orci. Duis auctor, libero lobortis sodales ultricies,
                    erat nibh venenatis urna, quis facilisis libero lorem eget augue.
                    Integer dolor quam, efficitur ullamcorper pellentesque et, hendrerit et est.
                    Maecenas euismod ultricies purus sed condimentum.
                </p>

                <h2>Nam lacinia lacinia urna eget bibendum</h2>

                <p>
                    Ut pulvinar justo nibh, sit amet viverra ipsum ornare ac.
                    Praesent viverra laoreet facilisis.
                    Sed erat purus, pulvinar eu nibh in, bibendum vulputate quam.
                    Sed sapien metus, <a href="#">convallis</a> sit <a href="#">amet odio</a> nec, sollicitudin porta libero.
                    Nam lacinia lacinia urna eget bibendum. Aenean at enim justo.
                    Donec rutrum, nisl et faucibus porttitor,
                    magna odio accumsan erat, a rutrum mi felis sit amet sapien.
                </p>

                <ul>
                    <li>Integer dolor quam</li>
                    <li>Etiam at consectetur enim</li>
                    <li>
                        Donec quis ante feugiat
                        <ol>
                            <li>Integer dolor quam</li>
                            <li>Etiam at consectetur enim</li>
                            <li>Donec quis ante feugiat</li>
                            <li>Nullam iaculis arcu</li>
                            <li>Nam rutrum ullamcorper euismod</li>
                            <li>Phasellus ligula odio</li>
                        </ol>
                    </li>
                    <li>Nullam iaculis arcu</li>
                    <li>Nam rutrum ullamcorper euismod</li>
                    <li>Phasellus ligula odio</li>
                </ul>

                <p>
                    Vestibulum hendrerit porttitor erat, in efficitur leo aliquet nec.
                    Donec quis ante feugiat, vestibulum justo vitae, tempus lorem.
                    Cras vestibulum, dui vel mollis semper, est massa rutrum risus,
                    vitae placerat elit libero ut felis. Quisque laoreet pellentesque enim.
                    Ut malesuada sagittis felis in scelerisque.
                    Nam rutrum ullamcorper euismod. Nunc tincidunt ut arcu eu consectetur.
                    Sed sed diam scelerisque, viverra erat id, facilisis massa.
                </p>

                <h3>Suspendisse sit amet leo ligula</h3>

                <p>
                    Nullam iaculis arcu ac nibh consequat, et lobortis massa lacinia.
                    Vivamus imperdiet sed tellus ac sodales.
                    Mauris a massa in magna sagittis rhoncus.
                    Ut posuere nulla nec enim accumsan molestie.
                    Pellentesque tempor mauris ac semper gravida.
                    Phasellus ligula odio, bibendum at consectetur eu, rutrum sed eros.
                    Nunc at commodo tortor. Pellentesque in ornare mi.
                    Suspendisse sit amet leo ligula. Proin sagittis laoreet porta.
                    Maecenas egestas in nibh ac eleifend.
                    Fusce quis diam facilisis, venenatis tortor nec, vehicula turpis.
                    Cras metus eros, ultrices ac euismod non, tincidunt nec est.
                    Nulla eleifend eros neque, sit amet elementum est iaculis nec.
                    Maecenas vel accumsan sapien. Duis ut purus sed augue tempor feugiat.
                </p>

            </div>
        </div>
    </div>
    <div class="clear"></div>


    <div class="breadcrumbs">
        <a href="#">Какие-то</a> &raquo;
        <a href="#">Хлебные</a> &raquo;
        <a href="#">Крошки</a> &raquo;
        <span>Рассыпались по сайту</span>
    </div>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
