

    <div class="pagination">
        <!-- a href="#">&laquo;&laquo;</a>
        <a href="#">&laquo;</a -->
        <?php foreach ($pagination as $item) { ?>
            <?php if ($item->current) { ?>
                <span><?=$item->number?></span>
            <?php } else { ?>
                <a href="<?=$item->url?>"><?=$item->number?></a>
            <?php } ?>
        <?php } ?>
        <!-- a href="#">&raquo;</a>
        <a href="#">&raquo;&raquo;</a -->
        <div class="clear"></div>
    </div>


