

    <div class="right-box right-box-300">
        <div class="box-padding">
            <div class="box">
                <h3>Активные темы на форуме</h3>
                <div class="announce-items">
                    <?php foreach (modules\forum\helpers\AnnounceTopicsHelper::getTopics() as $topic) { ?>
                        <a href="/forum/to-post?id=<?=$topic->last_post_id?>"><?=$topic->title?></a>
                    <?php } ?>
                </div>
                <p>[ <a href="/forum/tracker">Показать все</a> ]</p>
            </div>
            <div class="box">
                <h3>Еще какой-то блок</h3>
                <p>
                    Sed vel orci aliquam, consequat quam quis, suscipit tellus.
                    Etiam at consectetur enim. Sed et mauris lacus.
                    Fusce rutrum leo ante, <a href="#">placerat congue mauris</a> tincidunt vel.
                    Nunc eget nisi orci. Duis auctor, libero lobortis sodales ultricies,
                    erat nibh venenatis urna, quis facilisis libero lorem eget augue.
                    Integer dolor quam, efficitur ullamcorper pellentesque et, hendrerit et est.
                    Maecenas euismod ultricies purus sed condimentum.
                </p>
            </div>
        </div>
    </div>


