

    <div id="header" class="box">

        <a id="main-logo" href="/" title="На главную"></a>
        <div id="member-box">

            <div class="member-actions">
                <?php if (!Member::isAuth()) { ?>
                    <a href="/user/sign-in">Вход</a>
                    <a href="/user/register">Регистрация</a>
                <?php } else { ?>
                    <a href="/profile/private-messages">Личные сообщения (0)</a>
                    <a href="/profile/settings">Настройки аккаунта</a>
                    <a href="/user/sign-out">Выход</a>
                <?php } ?>
            </div>

            <?php if (Member::isAuth()) { ?>
                <div class="member-actions-extended">
                    <div class="action-group">
                        <div class="item"><a href="#">Another action</a></div>
                        <div class="item"><a href="#">Moderator action</a></div>
                        <div class="item"><a href="#">Admin action</a></div>
                    </div>
                    <div class="action-group">
                        <div class="item"><a href="#">Another action</a></div>
                        <div class="item"><a href="#">Moderator action</a></div>
                        <div class="item"><a href="#">Admin action</a></div>
                    </div>
                    <div class="action-group">
                        <div class="item"><a href="#">Another action</a></div>
                        <div class="item"><a href="#">Moderator action</a></div>
                        <div class="item"><a href="#">Admin action</a></div>
                    </div>
                </div>
            <?php } ?>

        </div>
        <div class="clear"></div>

    </div><!-- #header -->


