<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>


    <?php require 'main-menu.phtml'; ?>


    <div class="flex-container">


        <?php require 'right-box.phtml'; ?>


        <div class="left-box-pad-320">


            <?php require 'breadcrumbs.phtml'; ?>


            <div class="box-wrapper">
                <div class="box-padding">

                    <h1><?=$h1?></h1>

                    <form class="ajax-form"
                            action="/user/register/process"
                            method="post">
                        <div class="label">E-mail</div>
                        <div class="elem">
                            <input type="text"
                                    name="email"
                                    value=""
                                    autocomplete="off">
                            <span class="elem-message for-email"></span>
                        </div>
                        <div class="label">Логин (псевдоним)</div>
                        <div class="elem">
                            <input type="text"
                                    name="login"
                                    value=""
                                    autocomplete="off">
                            <span class="elem-message for-login"></span>
                        </div>
                        <div class="label">Пароль</div>
                        <div class="elem">
                            <input type="password"
                                    name="password"
                                    value="">
                            <span class="elem-message for-password"></span>
                        </div>
                        <div class="label">Подтвердите пароль</div>
                        <div class="elem">
                            <input type="password"
                                    name="confirm_password"
                                    value="">
                            <span class="elem-message for-confirm_password"></span>
                        </div>
                        <div class="half-box">
                            <div class="label">Защитный код</div>
                            <div class="elem">
                                <input class="short"
                                        type="text"
                                        name="protection_code"
                                        value=""
                                        autocomplete="off">
                            </div>
                        </div>
                        <div class="half-box">
                            <img class="protection-image"
                                    title="Кликни чтобы обновить"
                                    alt=""
                                    src="/protection-image.jpg?action=register&_=<?=md5(microtime())?>"
                                    onclick="this.src = '/protection-image.jpg?action=register&_' + Math.random();">
                            <span class="elem-message for-protection_code"></span>
                        </div>
                        <div class="clear"></div>
                        <div class="label">&nbsp;</div>
                        <div class="elem">
                            <input type="submit" value="Зарегистрироваться">
                        </div>
                        <div class="loading-cover"></div>
                    </form>
                    <p>
                        <a href="/user/sign-in">Уже есть аккаунт?</a>
                        |
                        <a href="/user/recovery">Забыли логин или пароль?</a>
                    </p>

                </div>
            </div>


        </div>


    </div>


    <?php require 'breadcrumbs.phtml'; ?>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
