<?php require 'header.phtml'; ?>


    <?php require 'top-box.phtml'; ?>
    <?php require 'main-menu.phtml'; ?>


    <div class="breadcrumbs">
        <a href="#">Какие-то</a> &raquo;
        <a href="#">Хлебные</a> &raquo;
        <a href="#">Крошки</a> &raquo;
        <span>Рассыпались по сайту</span>
    </div>


    <?php require 'right-box.phtml'; ?>


    <div class="left-box-pad-320">
        <div class="box-wrapper">
            <div class="box-padding">

                <h1><?=$pageH1?></h1>

            </div>
        </div>
    </div>
    <div class="clear"></div>


    <div class="breadcrumbs">
        <a href="#">Какие-то</a> &raquo;
        <a href="#">Хлебные</a> &raquo;
        <a href="#">Крошки</a> &raquo;
        <span>Рассыпались по сайту</span>
    </div>


    <?php require 'bottom-box.phtml'; ?>


<?php require 'footer.phtml'; ?>
